---
- name: Retrieve list of hosted zones in Route53 
  amazon.aws.route53_info:
    query: hosted_zone
  register: route53_info

## This is very specific to my use case here, I need to figure out
## a way to make it a little more generic, just in case there's ever 
## multiple zones. I can also argue that this is designed to only 
## work with a fresh AWS Blank OpenEnvironment from the Red Hat 
## Demo System so... Sorry if I ignore this for a bit.

##The fun regex at the end is there to remove a trailing period 
## that is somehow in the name string
- name: Setup DNS variables 
  ansible.builtin.set_fact:
    top_level_domain: '{{ route53_info.hosted_zones[0].name | regex_search(".*(?=\.)") }}'
    gateway_dns: gateway.{{ route53_info.hosted_zones[0].name | regex_search(".*(?=\.)") }}