---
- name: Setup automation controller dns check for acme challenge 
  amazon.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ controller_challenge_record }}"
    type: TXT
    value: "{{ controller_challenge_value }}"
    ttl: 60
    wait: yes
    identifier: "{{ hub_dns }}"
    region: "{{ aws_region }}"
    overwrite: yes
  when: 
    - controller_dns_challenge is changed 
    - controller_dns_challenge.challenge_data[controller_dns] is defined

- name: Setup Automation Hub dns check for acme challenge 
  amazon.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ hub_challenge_record }}"
    type: TXT
    value: "{{ hub_challenge_value }}"
    ttl: 60
    wait: yes
    identifier: "{{ hub_dns }}"
    region: "{{ aws_region }}"
    overwrite: yes
  when: 
    - hub_dns_challenge is changed 
    - hub_dns_challenge.challenge_data[hub_dns] is defined

- name: Setup EDA Controller dns check for acme challenge 
  amazon.aws.route53:
    profile: "{{ aws_profile }}"
    state: present 
    zone: "{{ top_level_domain }}"
    record: "{{ eda_challenge_record }}"
    type: TXT
    value: "{{ eda_challenge_value }}"
    ttl: 60
    wait: yes
    identifier: "{{ hub_dns }}"
    region: "{{ aws_region }}"
    overwrite: yes
  when: 
    - eda_dns_challenge is changed 
    - eda_dns_challenge.challenge_data[eda_dns] is defined